config/routes.rb
Rails.application.routes.draw do
  root "feed#show"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resource :profile, only: [:show, :update], controller: "users"
  namespace :users do
    patch "change_password", to: "passwords#update"
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :email_verifications, only: [:new, :create, :edit]
  end
end

app/models/user.rb
class User < ApplicationRecord
  include EmailVerification
  include PasswordReset
  include Authentication

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  before_validation :strip_extraneous_spaces

  validates :name, presence: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, uniqueness: {case_sensitive: false}

  private

  def strip_extraneous_spaces
    self.name = name&.strip
    self.email = email&.strip
  end
end

app/models/user/authentication.rb
module User::Authentication
  extend ActiveSupport::Concern

  included do
    has_secure_password
    attr_accessor :current_password
    validate :current_password_valid, on: :password_change
    validates :password, confirmation: true, length: {minimum: 8}, on: [:create, :password_change, :password_reset]
    has_many :app_sessions
  end

  class_methods do
    def create_app_session(email:, password:)
      user = User.find_by(email: email.downcase)
      user.app_sessions.create if user.present? && user.authenticate(password)
    end
  end

  def authenticate_app_session(app_session_id, token)
    app_sessions.find(app_session_id).authenticate_token(token)
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def current_password_valid
    errors.add(:current_password, :incorrect_password) unless matches_password_in_db?(current_password)
  end

  def matches_password_in_db?(current_password)
    digest = attribute_in_database(:password_digest)
    digest.present? && BCrypt::Password.new(digest).is_password?(current_password)
  end
end

app/models/user/email_verification.rb
module User::EmailVerification
  extend ActiveSupport::Concern

  included do
    has_secure_password :email_verification_token, validations: false
    after_commit :initiate_email_verification, on: :create
  end

  class_methods do
    def find_by_email_verification_id(id)
      message_verifier.verified(
        CGI.unescape(id),
        purpose: :email_verification
      )&.symbolize_keys => {user_id:, email_verification_token:}
      User.find(user_id).authenticate_email_verification_token(email_verification_token)
    rescue ActiveRecord::RecordNotFound, NoMatchingPatternError
      nil
    end
  end

  def initiate_email_verification
    update(email_verification_token: self.class.generate_unique_secure_token)
    UserMailer.with(user: self).email_verification(CGI.escape(email_verification_id)).deliver_now
  end

  def complete_email_verification
    update(email_verification_token: nil)
  end

  def email_verified?
    email_verification_token_digest.blank?
  end

  private

  def email_verification_id
    message_verifier.generate({
      user_id: id,
      email_verification_token: email_verification_token
    }, purpose: :email_verification, expires_in: 2.hours)
  end
end

app/models/user/password_reset.rb
module User::PasswordReset
  extend ActiveSupport::Concern

  included do
    has_secure_password :password_reset_token, validations: false
    before_save -> { self.password_reset_token = nil },
      if: -> { password_digest_change_to_be_saved.present? }
  end

  class_methods do
    def find_by_password_reset_id(id)
      message_verifier.verified(
        CGI.unescape(id),
        purpose: :password_reset
      )&.symbolize_keys => {user_id:, password_reset_token:}

      User.find(user_id).authenticate_password_reset_token(password_reset_token)
    rescue ActiveRecord::RecordNotFound, NoMatchingPatternError
      nil
    end
  end

  def reset_password
    update(password_reset_token: self.class.generate_unique_secure_token)
    app_sessions.destroy_all
    send_password_reset_email
  end

  private

  def send_password_reset_email
    UserMailer.with(user: self).password_reset(CGI.escape(password_reset_id)).deliver_now
    Rails.logger.info "password reset email sent to #{email}"
  end

  def password_reset_id
    message_verifier.generate({
      user_id: id,
      password_reset_token: password_reset_token
    }, purpose: :password_reset, expires_in: 2.hours)
  end
end

app/controllers/users/email_verifications_controller.rb
class Users::EmailVerificationsController < ApplicationController
  skip_email_verification

  def new
    @invalid_link = !!params[:invalid_link]
  end

  def create
    Current.user.initiate_email_verification
    redirect_to new_users_email_verification_path, status: :see_other
  end

  def edit
    @user = User.find_by_email_verification_id(params[:id])
    unless @user.present?
      redirect_to new_users_email_verification_path(invalid_link: true), status: :see_other
      return
    end
    @user.complete_email_verification
    recede_or_redirect_to root_path, status: :see_other, flash: {success: t(".success", name: @user.name)}
  end
end

app/controllers/users/password_resets_controller.rb
class Users::PasswordResetsController < ApplicationController
  skip_authentication
  before_action :load_user, only: [:edit, :update]

  def new
  end

  def create
    User.find_by(email: params[:email])&.reset_password
  end

  def edit
  end

  def update
    @user.assign_attributes(password_reset_params)
    if @user.save(context: :password_reset)
      @app_session = @user.app_sessions.create
      log_in(@app_session, false)

      flash[:success] = t(".success")
      recede_or_redirect_to root_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def load_user
    @user = User.find_by_password_reset_id(params[:id])

    unless @user.present?
      redirect_to new_users_password_reset_path,
        status: :see_other,
        flash: {
          error: t("users.password_resets.invalid_link")
        }
    end
  end

  def password_reset_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
  def update
    @user = Current.user
    @user.current_password = params.dig(:user, :current_password)
    @user.password = params.dig(:user, :password)
    @user.password_confirmation = params.dig(:user, :password_confirmation)
    if @user.save(context: :password_change)
      flash[:success] = t(".success")
      redirect_to profile_path, status: :see_other
    else
      render "users/show", status: :unprocessable_entity
    end
  end
end

app/controllers/users_controller.rb
# manages authenticated user
class UsersController < ApplicationController
  skip_authentication only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    unless @user.save
      render :new, status: :unprocessable_entity
      return
    end

    @organization = Organization.create(members: [@user])
    @app_session = @user.app_sessions.create
    log_in(@app_session, false)
    redirect_to new_users_email_verification_path, status: :see_other
  end

  def show
    @user = Current.user
  end

  def update
    @user = Current.user

    if @user.update(update_params)
      flash[:success] = t(".success")
      redirect_to profile_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/users/password_resets_helper.rb
module Users::PasswordResetsHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% content_for :title, t(".title") %>
<layout-columns class="columns is-centered">
  <layout-column class="column box is-5 mt-6 p-5 m-4">
    <h1 class="title has-text-centered">
      <%= t(".title") %>
    </h1>
    <%= form_with(
          model: @user,
          url: sign_up_path,
          class: "is-flex is-flex-direction-column"
        ) do |form| %>
      <div class="block">
        <%= form.label :name, class: "label" %>
        <%= form.text_field :name, class: "input" %>
      </div>
      <div class="block">
        <%= form.label :email, class: "label" %>
        <%= form.email_field :email, class: "input" %>
      </div>
      <div class="block">
        <%= form.label :password, class: "label" %>
        <%= form.password_field :password, class: "input" %>
      </div>
      <div class="block">
        <%= form.label :password_confirmation, class: "label" %>
        <%= form.password_field :password_confirmation, class: "input" %>
      </div>
      <%= form.submit t(".sign_up"),
            class: "button is-primary is-large
              is-align-self-flex-end mb-3 mt-3" %>
    <% end %>
    <%= tag.p class: "has-text-centered" do %>
      <%= t(".login_message")  %>
      <%= link_to t(".login"), login_path %>
    <% end if turbo_native_app? %>
  </layout-column>
</layout-columns>

app/views/users/show.html.erb
<% content_for :title, Current.user.name %>
<% if turbo_native_app? %>
  <%= button_to(
        t("shared.navbar.logout"),
        logout_path,
        method: :delete,
        data: {
          controller: "bridge--element",
          bridge_element_id: turbo_native_bridge_element_id(:logout),
          bridge_element_ios: {
            component: "bar_button",
            index: "0"
          }.to_json,
          bridge_element_android: {
            component: "menu_item",
            order: "0"
          }.to_json
        }
      ) %>
<% end %>
<%= turbo_frame_tag :user_details do %>
  <layout-columns class="columns is-centered">
    <layout-column class="column box is-5 mt-6 p-5 m-4">
      <h1 class="title has-text-centered">
        <%= t(".your_details") %>
      </h1>
      <%= form_with(
            model: @user,
            url: profile_path,
            class: "is-flex is-flex-direction-column"
          ) do |form| %>
        <div class="block">
          <%= form.label :name, class: "label" %>
          <%= form.text_field :name, class: "input" %>
        </div>
        <div class="block">
          <%= form.label :email, class: "label" %>
          <%= form.email_field :email, class: "input" %>
        </div>
        <%= form.submit t(".save_profile"), class: "button is-primary is-align-self-flex-end mb-3 mt-3" %>
        <%= render "shared/flashes" if turbo_frame_request? %>
      <% end %>
    </layout-column>
  </layout-columns>
  <%= turbo_stream.update :current_user_name do %>
    <%= Current.user.name %>
  <% end %>
<% end %>
<%= turbo_frame_tag :change_password do %>
  <layout-columns class="columns is-centered">
    <layout-column class="column box is-5 mt-6 p-5 m-4">
      <h1 class="title has-text-centered">
        <%= t(".change_password") %>
      </h1>
      <%= form_with(model: @user, url: users_change_password_path, class: "is-flex is-flex-direction-column") do |form| %>
        <div class="block">
          <%= form.label :current_password, value: t(".current_password"), class: "label" %>
          <%= form.password_field :current_password, class: "input" %>
        </div>
        <div class="block">
          <%= form.label :password, value: t(".new_password"), class: "label" %>
          <%= form.password_field :password, class: "input" %>
        </div>
        <div class="block">
          <%= form.label :password_confirmation, value: t(".new_password_confirmation"), class: "label" %>
          <%= form.password_field :password_confirmation, class: "input" %>
        </div>
        <%= form.submit t(".change_password_button"), class: "button is-primary is-align-self-flex-end mb-3 mt-3" %>
        <%= render "shared/flashes" if turbo_frame_request? %>
      <% end %>
    </layout-column>
  </layout-columns>
<% end %>