config/routes.rb
Rails.application.routes.draw do
  root "feed#show"
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resource :profile, only: [:show, :update], controller: "users"
  namespace :users do
    patch "change_password", to: "passwords#update"
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :email_verifications, only: [:new, :create, :edit]
  end
end

app/models/app_session.rb
class AppSession < ApplicationRecord
  belongs_to :user

  has_secure_password :token, validations: false

  before_create {
    self.token = self.class.generate_unique_secure_token
  }

  def to_h
    {
      user_id: user.id,
      app_session: id,
      token: token
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include MessageVerifier
  primary_abstract_class
end

app/models/concerns/message_verifier.rb
module MessageVerifier
  extend ActiveSupport::Concern

  class_methods do
    def message_verifier
      Rails.application.message_verifier(name)
    end
  end

  private

  def message_verifier
    Rails.application.message_verifier(self.class.name)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user, :app_session, :organization
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  include EmailVerification
  include PasswordReset
  include Authentication

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  before_validation :strip_extraneous_spaces

  validates :name, presence: true
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, uniqueness: {case_sensitive: false}

  private

  def strip_extraneous_spaces
    self.name = name&.strip
    self.email = email&.strip
  end
end

app/models/user/authentication.rb
module User::Authentication
  extend ActiveSupport::Concern

  included do
    has_secure_password
    attr_accessor :current_password
    validate :current_password_valid, on: :password_change
    validates :password, confirmation: true, length: {minimum: 8}, on: [:create, :password_change, :password_reset]
    has_many :app_sessions
  end

  class_methods do
    def create_app_session(email:, password:)
      user = User.find_by(email: email.downcase)
      user.app_sessions.create if user.present? && user.authenticate(password)
    end
  end

  def authenticate_app_session(app_session_id, token)
    app_sessions.find(app_session_id).authenticate_token(token)
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def current_password_valid
    errors.add(:current_password, :incorrect_password) unless matches_password_in_db?(current_password)
  end

  def matches_password_in_db?(current_password)
    digest = attribute_in_database(:password_digest)
    digest.present? && BCrypt::Password.new(digest).is_password?(current_password)
  end
end

app/models/user/email_verification.rb
module User::EmailVerification
  extend ActiveSupport::Concern

  included do
    has_secure_password :email_verification_token, validations: false
    after_commit :initiate_email_verification, on: :create
  end

  class_methods do
    def find_by_email_verification_id(id)
      message_verifier.verified(
        CGI.unescape(id),
        purpose: :email_verification
      )&.symbolize_keys => {user_id:, email_verification_token:}
      User.find(user_id).authenticate_email_verification_token(email_verification_token)
    rescue ActiveRecord::RecordNotFound, NoMatchingPatternError
      nil
    end
  end

  def initiate_email_verification
    update(email_verification_token: self.class.generate_unique_secure_token)
    UserMailer.with(user: self).email_verification(CGI.escape(email_verification_id)).deliver_now
  end

  def complete_email_verification
    update(email_verification_token: nil)
  end

  def email_verified?
    email_verification_token_digest.blank?
  end

  private

  def email_verification_id
    message_verifier.generate({
      user_id: id,
      email_verification_token: email_verification_token
    }, purpose: :email_verification, expires_in: 2.hours)
  end
end

app/models/user/password_reset.rb
module User::PasswordReset
  extend ActiveSupport::Concern

  included do
    has_secure_password :password_reset_token, validations: false
    before_save -> { self.password_reset_token = nil },
      if: -> { password_digest_change_to_be_saved.present? }
  end

  class_methods do
    def find_by_password_reset_id(id)
      message_verifier.verified(
        CGI.unescape(id),
        purpose: :password_reset
      )&.symbolize_keys => {user_id:, password_reset_token:}

      User.find(user_id).authenticate_password_reset_token(password_reset_token)
    rescue ActiveRecord::RecordNotFound, NoMatchingPatternError
      nil
    end
  end

  def reset_password
    update(password_reset_token: self.class.generate_unique_secure_token)
    app_sessions.destroy_all
    send_password_reset_email
  end

  private

  def send_password_reset_email
    UserMailer.with(user: self).password_reset(CGI.escape(password_reset_id)).deliver_now
    Rails.logger.info "password reset email sent to #{email}"
  end

  def password_reset_id
    message_verifier.generate({
      user_id: id,
      password_reset_token: password_reset_token
    }, purpose: :password_reset, expires_in: 2.hours)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate
  include VerifyEmail

  helper_method :turbo_frame_request?
  helper_method :turbo_native_app?
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  allow_unauthenticated
  skip_email_verification

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_authentication only: [:new, :create]
  skip_email_verification

  def new
  end

  def create
    @app_session = User.create_app_session(
      email: login_params[:email],
      password: login_params[:password]
    )

    unless @app_session
      flash.now[:danger] = t(".incorrect_details")
      render :new, status: :unprocessable_entity
      return
    end

    log_in(@app_session, remember_me)
    flash[:success] = t(".success")
    recede_or_redirect_to root_path, status: :see_other
  end

  def destroy
    log_out
    flash[:success] = t(".success")
    redirect_to login_path, status: :see_other
  end

  private

  def login_params
    @login_params ||= params.require(:user).permit(:email, :password, :remember_me)
  end

  def remember_me
    ActiveRecord::Type::Boolean.new.deserialize(login_params[:remember_me])
  end
end

app/controllers/users_controller.rb
# manages authenticated user
class UsersController < ApplicationController
  skip_authentication only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    unless @user.save
      render :new, status: :unprocessable_entity
      return
    end

    @organization = Organization.create(members: [@user])
    @app_session = @user.app_sessions.create
    log_in(@app_session, false)
    redirect_to new_users_email_verification_path, status: :see_other
  end

  def show
    @user = Current.user
  end

  def update
    @user = Current.user

    if @user.update(update_params)
      flash[:success] = t(".success")
      redirect_to profile_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    return t("piazza") unless content_for?(:title)
    return content_for(:title) if turbo_native_app?
    "#{content_for(:title)} | #{t("piazza")}"
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/turbo_native_helper.rb
module TurboNativeHelper
  def turbo_native_bridge_platform
    case request.user_agent
    when /Turbo Native iOS/
      "ios"
    when /Turbo Native Android/
      "android"
    else
      ""
    end
  end

  MAX_INT = 2**30 - 1

  def turbo_native_bridge_element_id(identifier)
    Zlib.crc32(identifier.to_s) % MAX_INT
  end
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_head.html.erb
<title><%= title %></title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= tag.meta name: "bridge-platform", content: turbo_native_bridge_platform %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "mobile", "data-turbo-track": "reload" if turbo_native_app? %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>
  <body>
    <%= render "shared/navbar" unless turbo_native_app? %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<div class="container is-fluid" data-turbo-cache="false">
  <% flash.each do |level, message| %>
    <%= tag.div class: "notification is-#{level} is-light has-text-centered mt-4" do %>
      <%= message %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar is-link" data-controller="navbar">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <strong class="is-size-3">Piazza</strong>
    <% end %>
    <a role="button" class="navbar-burger" data-navbar-target="burger" data-action="navbar#toggle">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>
  <navbar-menu class="navbar-menu" data-navbar-target="menu">
    <div class="navbar-start">
      <%= link_to t(".create_ad"), "#", class: "navbar-item" %>
      <%= link_to t(".messages"), "#", class: "navbar-item" if logged_in? %>
    </div>
    <div class="navbar-end">
      <%= tag.div class: "navbar-item has-dropdown is-hoverable mr-4" do %>
        <%= link_to Current.user.name, profile_path, id: "current_user_name", class: "navbar-link" %>
        <div class="navbar-dropdown is-right">
          <%= link_to t(".profile"), profile_path, class: "navbar-item" %>
          <%= link_to t(".my_ads"), "#", class: "navbar-item" %>
          <%= link_to t(".saved_ads"), "#", class: "navbar-item" %>
          <hr class="navbar-divider">
          <%= link_to t(".logout"), logout_path, class: "navbar-item", data: { turbo_method: :delete } %>
        </div>
      <% end if logged_in? %>
      <%= tag.div class: "navbar-item" do %>
        <div class="buttons">
          <%= link_to t(".sign_up"), sign_up_path, class: "button is-primary" %>
          <%= link_to t(".login"), login_path, class: "button is-light" %>
        </div>
      <% end unless logged_in? %>
    </div>
  </navbar-menu>
</nav>